import {
  LayoutDashboard,
  User,
  Dumbbell,
  Utensils,
  Footprints,
  Sparkles,
  Target,
  Users,
  Trophy,
  Bot,
  Settings as SettingsIcon,
} from 'lucide-react'

export const NAVIGATION_CATEGORIES = {
  DAILY: 'Daily Tracking',
  COMMUNITY: 'Group & Progress',
  ACCOUNT: 'Preferences',
}

export const NAV_ITEMS = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: LayoutDashboard,
    category: NAVIGATION_CATEGORIES.DAILY,
    description: 'Overview of your daily metrics, group progress, and active streak.',
    isPrimaryMobile: true,
  },
  {
    id: 'exercise',
    label: 'Exercise',
    icon: Dumbbell,
    category: NAVIGATION_CATEGORIES.DAILY,
    description: 'Log and track workouts, sets, duration, and exercise history.',
    isPrimaryMobile: true,
  },
  {
    id: 'food-calories',
    label: 'Food & Calories',
    icon: Utensils,
    category: NAVIGATION_CATEGORIES.DAILY,
    description: 'Monitor daily meals, macros, and calorie targets.',
    isPrimaryMobile: true,
  },
  {
    id: 'steps',
    label: 'Steps',
    icon: Footprints,
    category: NAVIGATION_CATEGORIES.DAILY,
    description: 'Daily step counter, distance tracking, and walking goals.',
    isPrimaryMobile: false,
  },
  {
    id: 'spirituality',
    label: 'Spirituality',
    icon: Sparkles,
    category: NAVIGATION_CATEGORIES.DAILY,
    description: 'Daily reflection, gratitude, mindfulness, and spiritual habits.',
    isPrimaryMobile: false,
  },
  {
    id: 'goals',
    label: 'Goals',
    icon: Target,
    category: NAVIGATION_CATEGORIES.COMMUNITY,
    description: 'Personal targets, group challenges, and milestone tracking.',
    isPrimaryMobile: false,
  },
  {
    id: 'group-activity',
    label: 'Group Activity',
    icon: Users,
    category: NAVIGATION_CATEGORIES.COMMUNITY,
    description: 'Live activity feed, member updates, and community encouragement.',
    isPrimaryMobile: false,
  },
  {
    id: 'leaderboard',
    label: 'Leaderboard',
    icon: Trophy,
    category: NAVIGATION_CATEGORIES.COMMUNITY,
    description: 'Weekly rankings, points, streaks, and healthy group competition.',
    isPrimaryMobile: true,
  },
  {
    id: 'ai-coach',
    label: 'AI Coach',
    icon: Bot,
    category: NAVIGATION_CATEGORIES.COMMUNITY,
    description: 'Intelligent recommendations, habit analysis, and fitness guidance.',
    isPrimaryMobile: false,
  },
  {
    id: 'profile',
    label: 'My Profile',
    icon: User,
    category: NAVIGATION_CATEGORIES.ACCOUNT,
    description: 'Personal stats, biometric details, badges, and fitness history.',
    isPrimaryMobile: false,
  },
  {
    id: 'settings',
    label: 'Settings',
    icon: SettingsIcon,
    category: NAVIGATION_CATEGORIES.ACCOUNT,
    description: 'App preferences, notifications, privacy, and account configuration.',
    isPrimaryMobile: false,
  },
]

